location: .gitman
sources:
        - name: controllers_brubotics
          type: git
          repo: git@github.com:mrs-brubotics/controllers_brubotics.git
          sparse_paths:
                  -
          rev: master
          link: ros_packages/controllers_brubotics
          scripts:
                  - git submodule update --init --recursive
        - name: trackers_brubotics
          type: git
          repo: git@github.com:mrs-brubotics/trackers_brubotics.git
          sparse_paths:
                  -
          rev: master
          link: ros_packages/trackers_brubotics
          scripts:
                  - git submodule update --init --recursive
        - name: testing_brubotics
          type: git
          repo: git@github.com:mrs-brubotics/testing_brubotics.git
          sparse_paths:
                  -
          rev: master
          link: ros_packages/testing_brubotics
          scripts: 
                  - git submodule update --init --recursive
        - name: planners_brubotics
          type: git
          repo: git@github.com:mrs-brubotics/planners_brubotics.git
          sparse_paths:
                  -
          rev: master
          link: ros_packages/planners_brubotics
          scripts: 
                  - git submodule update --init --recursive
#        - name: visualization_brubotics
#          type: git
#          repo: git@github.com:mrs-brubotics/visualization_brubotics.git
#          sparse_paths:
#                  -
#          rev: master
#          link: ros_packages/visualization_brubotics
#          scripts: 
#                  - git submodule update --init --recursive
        - name: matlab_graphs
          type: git
          repo: git@github.com:mrs-brubotics/MatlabGraphs.git
          sparse_paths:
                  -
          rev: master
          link: useful_files/matlab_graphs
          scripts:
                  - git submodule update --init --recursive
        - name: documentation_brubotics
          type: git
          repo: git@github.com:mrs-brubotics/documentation_brubotics.git
          sparse_paths:
                  -
          rev: master
          link: ros_packages/documentation_brubotics
          scripts: 
                  - git submodule update --init --recursive
