location: .gitman
sources:
# ROS packages:
  - repo: https://github.com/mrs-brubotics/testing_brubotics.git
    name: testing_brubotics
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/controllers_brubotics.git
    name: controllers_brubotics
    rev: MJ_Fix_Config_Files_Issue #master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/trackers_brubotics.git
    name: trackers_brubotics
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/planners_brubotics.git
    name: planners_brubotics
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/visualization_brubotics.git
    name: visualization_brubotics
    rev: main
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
#  - repo: git@github.com:mrs-brubotics/documentation_brubotics.git
#    name: documentation_brubotics
#    rev: main
#    type: git
#    sparse_paths:
#      -
#    links:
#      -
#    scripts:
#      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/fbstab.git
    name: fbstab
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
sources_locked:
# ROS packages:
  - repo: git@github.com:mrs-brubotics/controllers_brubotics.git
    name: controllers_brubotics
    rev: RaphaelMerge
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/trackers_brubotics.git
    name: trackers_brubotics
    rev: MergeRaphael
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:mrs-brubotics/testing_brubotics.git
    name: testing_brubotics
    rev: RaphaelMerge
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive 
  - repo: git@github.com:mrs-brubotics/fbstab.git
    name: fbstab
    rev: a75544eebcb54622a90cd2c93e3554318c19f200
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
